title: Chris Holmes
description: 
author: C. Holmes
avatar: /holmech.jpeg
email: holmech.dev@gmail.com
github: https://github.com/holmech-dev
docker: https://hub.docker.com/u/holmec
linkedin: https://www.linkedin.com/in/chris-holmes1/


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

social:
  name: Chris Holmes
  links:
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
